### ISSUE TITLE
Can't play in multiplayer 1.20.4 Fabric

### ISSUE THREAD

**Issue by d1ret** [DIDIRUS4/AstralRinth#11]
### Describe the bug

When logging into the local server, the error is: "Login error: Invalid Minecraft session"
![image](https://github.com/DIDIRUS4/AstralRinth/assets/67980548/58e550c4-91a2-4434-a2c5-dec714fbb3fe)

### Steps to reproduce

1. One player creates a world and opens networks.
2. The second player adds a local IP and port to the list of servers.
3. Error.

### Expected behavior

Успешная авторизация

Or is this how it should be, and this is not a bug?

**Comment by DIDIRUS4** [comment]
This is not a launcher issue. By default, to play in the local world with a friend, you must have a license. You can start the local server separately and set online-mode=false in the server.properties minecraft core settings (for example: PaperMC, Fabric) 

- The launcher gives you the opportunity to launch and control the game without a license, while the game functions/mechanics are not changed by us. 

- Thus, you can still play on pirated servers without access to Microsoft authorization services.
