### ISSUE TITLE
Сортировка

### ISSUE THREAD

**Issue by PovarRavop** [DIDIRUS4/AstralRinth#14]
### Describe the bug

Не сохраняются настройки группировки и сортировки профилей

### Steps to reproduce

1. Из выпадающего списка группировки выбрать Лоадер
2. Из выпадающего списка сортировки выбрать Версия игры
3. Перейти на главную страницу или закрыть приложение
4. Перейти обратно в библиотеку
5. Настройки будут сброшены

### Expected behavior

При перезаходе в библиотеку параметры сортировки и группировки не должны сбрасываться

### System information

Используется операционная система Windows
Локальная установленная версия v0.7.206 • Beta

**Comment by DIDIRUS4** [comment]
В Modrinth разве не сбрасываются ?

**Comment by PovarRavop** [comment]
Да, сбрасывается. Но группировка по категориям нет

**Comment by DIDIRUS4** [comment]
Реализовано. Запрос на пулл реквест https://github.com/DIDIRUS4/AstralRinth/pull/15

Скоро будет обновление в релизах v0.7.208 • Beta

**Comment by PovarRavop** [comment]
Спасибо за ответ. Но я забыл уточнить, что настройки также сбрасываются после перезахода в приложение

**Comment by DIDIRUS4** [comment]
![image](https://github.com/DIDIRUS4/AstralRinth/assets/77334306/acf6327e-3bda-4416-98e1-7c965005402f)

Сохранение подобного в конфиг не планируется из-за возможных ошибок в будущем
