### ISSUE TITLE
1.21 NeoForge

### ISSUE THREAD

**Issue by Rusmer** [DIDIRUS4/AstralRinth#16]
### Describe the solution you'd like

Add a 1.21 NeoForge

**Comment by DIDIRUS4** [comment]
A known problem. A decision is expected from the original authors (There is already a Pull Request on their part). But maybe I will personally fix the compilation error and implement their Pull Request in our AstralRinth.

**Comment by DIDIRUS4** [comment]
### Checkout actions workflow and our pull requests.

- https://github.com/DIDIRUS4/AstralRinth/pull/17

**Comment by DIDIRUS4** [comment]
### Dirty development builds available here
- https://github.com/DIDIRUS4/AstralRinth/releases/download/ARF-v0.7.2/DEV_BUILD_windows-latest-0.7.209.zip
- https://github.com/DIDIRUS4/AstralRinth/releases/download/ARF-v0.7.2/DEV_BUILD_ubuntu-22.04-0.7.209.zip
- https://github.com/DIDIRUS4/AstralRinth/releases/download/ARF-v0.7.2/DEV_BUILD_macos-latest-0.7.209.zip

After some time, I will merge this branch with the beta branch, provided that no errors occur in the future.
