### ISSUE TITLE
Installing 1.20.4 with Forge loader fails (all other loaders install fine)

### ISSUE THREAD

**Issue by sepsol** [DIDIRUS4/AstralRinth#18]
### Describe the bug

Installing 1.20.4 with Forge fails with the following error:

![image](https://github.com/DIDIRUS4/AstralRinth/assets/47871887/8143398c-facf-46bd-9096-a9b48b14a78c)

### Steps to reproduce

Try to install `1.20.4` with `Forge`.

### Expected behavior

Successful installation like all other loaders.

### System information

- Windows 11 version 23H2 build 22631.3810
- Java version: `zulu17.50.19-ca-jre17.0.11-win_x64` (recommended by launcher)
- AstralRinth version 0.7.208 (Beta)

**Comment by DIDIRUS4** [comment]
Try install latest DEV_BUILD v0.7.209 • Beta
Check this issue comment and follow to links for download dirty releases
- https://github.com/DIDIRUS4/AstralRinth/issues/16#issuecomment-2203081882

### Main issue
- https://github.com/DIDIRUS4/AstralRinth/issues/16
### Pull Request
- https://github.com/DIDIRUS4/AstralRinth/pull/17

**Comment by sepsol** [comment]
Yep, installing Forge 1.20.4 worked fine with v0.7.209. Thanks!
