### ISSUE TITLE
Improved navigation through the interface

### ISSUE THREAD

**Issue by EVOR-Lab** [DIDIRUS4/AstralRinth#2]
### Is your suggested enhancement related to a problem? Please describe.

Every time after installing a mod, you have to go back to the mod position and this often gets boring.

### Describe the solution you'd like

1.  I would like the interface to have arrows like in the browser

2. The position of the slider (height) remained the same after leaving the mod page to the mod search page.

### Additional context

![image](https://github.com/DIDIRUS4/AstralRinth/assets/93032902/f9f62840-1f94-4ed2-815c-ea299f693cea)
I see it something like this

![image](https://github.com/DIDIRUS4/AstralRinth/assets/93032902/7f5cba76-1684-41e2-8352-3d50c6b0ad46)
In Modrinth it looks like this

**Comment by DIDIRUS4** [comment]
![Снимок экрана 2024-02-24 в 20 46 28](https://github.com/DIDIRUS4/AstralRinth/assets/77334306/b132df8c-7f0e-4c77-b1ca-7a846a10b857)

I think enhancement issue can be closed. If you want a feedback or suggestion, follow / find us in Telegram / Discord

Discord • https://discord.gg/7XkGYJbtZg
Telegram • https://t.me/AstraliumOrg
