### ISSUE TITLE
Cannot login to Modrinth due to Captcha Error

### ISSUE THREAD

**Issue by sepsol** [DIDIRUS4/AstralRinth#20]
### Describe the bug

When trying to login to my Modrinth account, I get the following error:

```
An error occurred
Error: Failed to login with error Captcha Error. Try resubmitting the form.
```

![image](https://github.com/DIDIRUS4/AstralRinth/assets/47871887/99085a94-bb91-4483-ba41-457a6e0907b4)

### Steps to reproduce

Try logging in to your Modrinth account.

### Expected behavior

Successful login.

### System information

- Windows 11 version 23H2 build 22631.3810
- AstralRinth version 0.7.209 (Beta)

**Comment by Adzetko** [comment]
I can confirm I have the same problem

**Comment by DIDIRUS4** [comment]
### This problem is present in the original repository
- https://github.com/modrinth/code/issues/1147

**Comment by DIDIRUS4** [comment]
Modrinth website uses CloudFlare API Captcha under login modal view.
![image](https://github.com/DIDIRUS4/AstralRinth/assets/77334306/738d326f-2426-425c-8273-17aa15efcd98)

**Comment by DIDIRUS4** [comment]
Fixed by modrinth in latest commits. Actually I merged pull request https://github.com/DIDIRUS4/AstralRinth/pull/28 into beta branch.

Version v0.8.003
