### ISSUE TITLE
Modrinth Duplicate Instance doesn't work if there are Empty Folders inside the instance it throws IO Error.

### ISSUE THREAD

**Issue by Kristijan1001** [DIDIRUS4/AstralRinth#29]
### Please confirm the following.

- [X] I checked the [existing issues](https://github.com/modrinth/code/issues) for duplicate problems
- [X] I have tried resolving the issue using the [support portal](https://support.modrinth.com)
- [X] I have ensured my Modrinth App installation is up to date

### What version of the Modrinth App are you using?

v0.8.004 • Beta

### What operating systems are you seeing the problem on?

Windows

### Describe the bug

![AstralRinth_App_TGihi5cQtu](https://github.com/user-attachments/assets/03e2e77a-71a3-45cc-8f4f-c973fff52cd8)
If there is an empty folder in the instance it throws and error being unable to duplicate the instance. To fix it simply creating .txt file in the empty folders works.

### Steps to reproduce

1. Duplicate Instance.
2.  Fail.
3. Create Dummy Txt in empty folders
4. Duplicate Instance
5. Works

### Expected behavior

To Create the instance

**Comment by DIDIRUS4** [comment]
Version 0.8.5 with patches will be released soon. It will be without the support of some of the features that are currently available and as close as possible to the original product.

This issue possibly fixed in latest ModrinthApp and new AstralRinthApp in feature-clean branch.
