### ISSUE TITLE
[`0.8.503`] AstralRinth fails to import MRPack files

### ISSUE THREAD

**Issue by UltimatChamp** [DIDIRUS4/AstralRinth#33]
![image](https://github.com/user-attachments/assets/4a86e951-83b9-4ff2-83b5-28ce00e6d37f)

<hr>

Importing an instance from another launcher, also fails now...

![image](https://github.com/user-attachments/assets/caeb8778-d619-4f74-bfcc-98b185e01f2b)

**Comment by DIDIRUS4** [comment]
First trouble fixed in v0.8.504. Release is coming soon
