### ISSUE TITLE
Bug with closing launcher in fullsecreen

### ISSUE THREAD

**Issue by remixofc** [DIDIRUS4/AstralRinth#34]
When the launcher is in full-screen mode, when hovering over the very top right corner and pressing the close button, the launcher does not close with the first click.

**Comment by DIDIRUS4** [comment]
## Provide addition information about this issue
• Do you use "Native decorations" in the launcher settings?

• Have you checked this problem on the original launcher? (Logging into a Microsoft account is not required for the stages of interaction with the launcher interface (without launching the Minecraft game))

## Can't be reproduced 
• The problem does not show up on my macOS Sequoia 15.0 Beta 8.
