### ISSUE TITLE
Can't do multiplayer with mods (getsockopt error)

### ISSUE THREAD

**Issue by KrokusAstra** [DIDIRUS4/AstralRinth#35]
Hi! I can't connect to friend with multiplayer mods like e4mc and opentoonline.
It gives me getsockopt error. I added everything i could to windows defender (java files inside astralrinth folder C:\Users\Amarillis\AppData\Roaming\com.modrinth.theseus\meta\java_versions\zulu8.78.0.19-ca-jre8.0.412-win_x64\bin) and checked if it's private, but error is still here. What should i do?
![image](https://github.com/user-attachments/assets/48f041aa-632d-43cb-8e12-35180b601b37)
![image](https://github.com/user-attachments/assets/dced575f-9f58-4adf-89f4-dd6bf76aa1f1)
![image](https://github.com/user-attachments/assets/75e90ebd-deea-482a-8fcf-5c3db8134bf2)
![image](https://github.com/user-attachments/assets/fe41144a-40ad-4b9b-aa06-11a4cce5c355)

**Comment by DIDIRUS4** [comment]
## Up to date?
- Dir path `com.modrinth.theseus` is deprecated in Modrinth and AstralRinth too. We have incompatible changes with default dirs in new version. Modrinth dir path is `ModrinthApp` and AstralRinth dir path is `AstralRinthApp`
- Please, try install latest version of AstralRinth and reproduce again this issue.
- You can try get support from community in our telegram chat _(RU Language priority)_ • https://astralium.su/f/telegram/astralium -> check pinned post and go to channel chat
