### ISSUE TITLE
Can't download update

### ISSUE THREAD

**Issue by plemyashkin01** [DIDIRUS4/AstralRinth#38]
![image](https://github.com/user-attachments/assets/b06f0176-b69e-4758-b483-bdb861cd75b4)

**Comment by DIDIRUS4** [comment]
AstralRinth doesn't use Modrinth home directory

**Comment by plemyashkin01** [comment]
This folder was empty, when I install AstralRinth

**Comment by DIDIRUS4** [comment]
> @DIDIRUS4 This folder was empty, when I install AstralRinth

The system notice to make sure that you have access to this folder. 
- I recommend checking the rights in the properties, and also make sure that the installer is running on behalf of the admin rights

**Comment by plemyashkin01** [comment]
@DIDIRUS4 
![image](https://github.com/user-attachments/assets/50b1d56f-0ee9-456f-8762-5f5c1c96a41e)
How to start it with admin rights?

**Comment by plemyashkin01** [comment]
Thanks, it works
