### ISSUE TITLE
Some Fields are Placed Randomly in `modrinth.index.json` When Exporting

### ISSUE THREAD

**Issue by UltimatChamp** [DIDIRUS4/AstralRinth#40]
<img width="450px" src="https://github.com/user-attachments/assets/16947f16-7e57-4a46-b13a-5d79bed06ff1" />

I'll try my best to explain this issue.
It looks like the `sha1` and `sha512` fields are placed, randomly, while exporting the modpack. Same is the case for `client`-`server` and the `minecraft`-`loader` fields. The image shows a diff between two different, simultaneous exports. This is an issue for modpack developers, who host their modpacks files on **GitHub**.

**Comment by DIDIRUS4** [comment]
Is this problem reproducing in the Modrinh App?

**Comment by UltimatChamp** [comment]
> Is this problem reproducing in the Modrinh App?

Yeah, it does happen on Modrinth App `0.8.8`.

**Comment by DIDIRUS4** [comment]
> > Is this problem reproducing in the Modrinh App?
> 
> Yeah, it does happen on Modrinth App `0.8.8`. I've reported it to them: [modrinth#2510](https://github.com/modrinth/code/issues/2510).


Have you tried offering this issue in the original repository? If yes - please provide a link to issue. We try not to fix the launcher, but only to support our idea and upgrade to the latest versions of the original

**Comment by UltimatChamp** [comment]
Yes, I've already reported them and provided the link, lol. (the message you are replying to)

**Comment by DIDIRUS4** [comment]
Modrinth release 0.8.9. I'll upstream as I can. Maybe this update fix your problem
