### ISSUE TITLE
Visual bug with the mod update icon

### ISSUE THREAD

**Issue by EVOR-Lab** [DIDIRUS4/AstralRinth#6]
### Describe the bug

This bug is not so serious but it would be nice to eliminate it (to the delight of perfectionists), it appears when the user clicks on the refresh button the Modrinth icon looks too big (I will add a picture below)

### Steps to reproduce

1. Go to any Modpack
3. Find a mod that has not been updated 
4. Click on the update button 
5. You will see a visual bug

### Expected behavior

The icon will be of normal size

### System information

Windows 10 64x

### Additional context

![image](https://github.com/DIDIRUS4/AstralRinth/assets/93032902/806a3bf0-2e05-4297-92d6-a7d0977759da)

**Comment by DIDIRUS4** [comment]
![image](https://github.com/DIDIRUS4/AstralRinth/assets/77334306/f43a85f1-a8be-43d5-91ce-f7dd799b79bd)

A new commit has just been pushed with this fix. The beta release v03 will be pushed in a few minutes.

In additional other problem is fixed too
![image](https://github.com/DIDIRUS4/AstralRinth/assets/77334306/8f1f3048-163d-4443-875d-b3a42a92f6a7)

- [Check pushed commit on beta branch](https://github.com/DIDIRUS4/AstralRinth/commit/58cd0f47fe57495f1e6e97b30d8c46ae36739b81)
