### ISSUE TITLE
[request] flatpak build

### ISSUE THREAD

**Issue by gmankab** [DIDIRUS4/AstralRinth#8]
### Is your suggested enhancement related to a problem? Please describe.

no

### Describe the solution you'd like

hello

flatpaks are main packaging format for steam os, fedora, fedora atomic, and vanilla os

can you please provide flatpak builds?

it could be a selfhosted repo, or just .flatpak file on releases page

### Describe alternatives you've considered

no

### Additional context

no

**Comment by DIDIRUS4** [comment]
We apologize for this, but we have no plans to add this.
