### ISSUE TITLE
When switching the launcher from full window to window it disappears but remains running

### ISSUE THREAD

**Issue by evorokk** [DIDIRUS4/AstralRinth#9]
### Describe the bug

Initially (personally with me) launches Launcher initially in a window not on the full screen, but if you transfer the window to full windowed mode and back to windowed, the visual part disappears completely but the program remains to work (this bug appears rarely but still present and if I find out the details I will add to this post). 

### Steps to reproduce

1. click on
![image](https://github.com/DIDIRUS4/AstralRinth/assets/93032902/eda15278-733a-4f5d-9bd9-d1c0e0d67136)
2. click agian

### System information

Windows 10, the latest version of the Launcher

**Comment by DIDIRUS4** [comment]
The problem can't be reproduced :(
